# Generated by Django 2.2.4 on 2019-08-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
