# Generated by Django 2.2.4 on 2019-08-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190830_0537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetModel',
            new_name='Pet',
        ),
    ]
