# Generated by Django 2.2.4 on 2019-08-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
