# Generated by Django 2.2.4 on 2019-08-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
